1.0.0|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/+unimixins-all-1.7.10-0.1.17.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/Armourers-Workshop-1.7.10-0.48.5.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/bspkrs.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/CustomNPC-Plus-1.9.3-beta2.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/dbcproject-8723fe9-minimal+8723fe9eb1-dirty.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/DragonBlockC-v1.4.85.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/extraarmor.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/geckolib-unofficial-1.7.10-1.0.3.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JBRA-Client-v1.6.52.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JFamilyC-v1.2.18.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JRMCore-v1.3.51.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JYearsC-v1.2.5.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/NBArmors-2.7.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/npcaw-1.1.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/npcdbc-1.0-24w36-03-save_fix.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/npcgecko-1.0.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/OptiFine_1.7.10_HD_U_E7.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/PluginMod-5.1.jar|
