1.0.0|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/+unimixins-all-1.7.10-0.2.1.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/Armourers-Workshop-1.7.10-0.48.5.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/DragonBlockC-v1.4.85.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JBRA-Client-v1.6.52.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JFamilyC-v1.2.17.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JRMCore-v1.3.51.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JYearsC-v1.2.3.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/JinRyuu's-HDSkins-Mod-1.7.10-v1.3.1.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/NBArmors-3.1.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/beddium-mc1.7.10-1.2.3-j21.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/dbcproject-39b46d6-pojav+39b46d6d08-dirty.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/falsepatternlib-mc1.7.10-1.10.7.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/falsetweaks-mc1.7.10-4.4.0.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/lwjgl3ify-3.0.15.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/npcdbc-1.2.1.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/smart_particles+mc1.7.10-7.10.9a-Forge.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/standalone-JaninoLoader-1.0.2.jar|
