1.0.0|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/unimixins-all-1.7.10-0.1.17.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/Armourers-Workshop-1.7.10-0.48.5.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/bspkrs.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/CustomNPC-Plus-1.9.3-beta2.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/dbcproject-8723fe9-minimal+8723fe9eb1-dirty.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/DragonBlockC-v1.4.85.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/ExtraAmor.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/geckolib-unofficial-1.7.10-1.0.3.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/JBRA-Client-v1.6.52.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/JFamilyC-v1.2.18.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/JRMCore-v1.3.51.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/JYearsC-v1.2.5.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/NBArmors-2.7.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/npcaw-1.1.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/npcdbc-1.0-24w36-03-save_fix.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/npcgecko-1.0.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/OptiFine_1.7.10_HD_U_E7.jar|
https://github.com/dbcbrasil/modpack/raw/refs/heads/main/pojav/PluginMod-5.1.jar|
